In [1]:
import pandas as pd

In [13]:
cd/users/Sandhya/Desktop

/Users/sandhya/Desktop

In [14]:
sheet1=pd.read_excel(r'Data Analyst Intern Assignment - Excel.xlsx',sheet_name='UserDetails.csv')
sheet2=pd.read_excel(r'Data Analyst Intern Assignment - Excel.xlsx',sheet_name='CookingSessions.csv')
sheet3=pd.read_excel(r'Data Analyst Intern Assignment - Excel.xlsx',sheet_name='OrderDetails.csv')

In [15]:
#Combine sheet 2 and 3 
merged_data=pd.merge(sheet3,sheet2,on='Session ID',how='left')
merged_data=merged_data.drop(columns=['User ID_x','Meal Type_x','Dish Name_x'])
merged_data=merged_data.rename(columns={'User ID_y':'User ID','Meal Type_y':'Meal Type','Dish Name_y':'Dish Name'})
merged_data

,Order ID,Order Date,Order Status,Amount (USD),Time of Day,Rating,Session ID,User ID,Dish Name,Meal Type,Session Start,Session End,Duration (mins),Session Rating
0,1001.0,2024-12-01,Completed,15.0,Night,5.0,S001,U001,Spaghetti,Dinner,2024-12-01 19:00:00,2024-12-01 19:30:00,30.0,4.5
1,1002.0,2024-12-01,Completed,10.0,Day,4.0,S002,U002,Caesar Salad,Lunch,2024-12-01 12:00:00,2024-12-01 12:20:00,20.0,4.0
2,1003.0,2024-12-02,Canceled,12.5,Night,NaN,S003,U003,Grilled Chicken,Dinner,2024-12-02 19:30:00,2024-12-02 20:10:00,40.0,4.8
3,1004.0,2024-12-02,Completed,8.0,Morning,4.0,S004,U001,Pancakes,Breakfast,2024-12-02 07:30:00,2024-12-02 08:00:00,30.0,4.2
4,1005.0,2024-12-03,Completed,9.0,Day,4.0,S005,U004,Caesar Salad,Lunch,2024-12-03 13:00:00,2024-12-03 13:15:00,15.0,4.7
5,1006.0,2024-12-03,Completed,14.0,Night,4.0,S006,U002,Spaghetti,Dinner,2024-12-03 18:30:00,2024-12-03 19:00:00,30.0,4.3
6,1007.0,2024-12-04,Completed,13.5,Night,4.0,S007,U005,Grilled Chicken,Dinner,2024-12-04 18:00:00,2024-12-04 18:45:00,45.0,4.6
7,1008.0,2024-12-04,Canceled,11.0,Day,NaN,S008,U003,Veggie Burger,Lunch,2024-12-04 13:30:00,2024-12-04 13:50:00,20.0,4.4
8,1009.0,2024-12-05,Completed,12.0,Night,5.0,S009,U001,Grilled Chicken,Dinner,2024-12-05 19:00:00,2024-12-05 19:40:00,40.0,4.9
9,1010.0,2024-12-05,Completed,7.0,Morning,4.0,S010,U002,Oatmeal,Breakfast,2024-12-05 07:00:00,2024-12-05 07:10:00,10.0,4.1
10,1011.0,2024-12-06,Completed,8.5,Morning,4.0,S011,U003,Pancakes,Breakfast,2024-12-06 08:00:00,2024-12-06 08:30:00,30.0,4.6
11,1012.0,2024-12-06,Completed,12.5,Night,4.0,S012,U004,Spaghetti,Dinner,2024-12-06 19:00:00,2024-12-06 19:40:00,40.0,4.7
12,1013.0,2024-12-07,Completed,9.0,Day,4.0,S013,U005,Caesar Salad,Lunch,2024-12-07 12:30:00,2024-12-07 13:00:00,30.0,4.4
13,1014.0,2024-12-07,Completed,13.0,Night,5.0,S014,U006,Grilled Chicken,Dinner,2024-12-07 18:00:00,2024-12-07 18:45:00,45.0,4.8
14,1015.0,2024-12-08,Completed,14.0,Night,5.0,S015,U007,Spaghetti,Dinner,2024-12-08 19:30:00,2024-12-08 20:10:00,40.0,5.0
15,1016.0,2024-12-08,Completed,11.0,Day,4.0,S016,U008,Veggie Burger,Lunch,2024-12-08 13:30:00,2024-12-08 13:50:00,20.0,4.3

In [16]:
merged_data=pd.merge(merged_data,sheet1,on='User ID',how='left')
merged_data

,Order ID,Order Date,Order Status,Amount (USD),Time of Day,Rating,Session ID,User ID,Dish Name,Meal Type,...,Duration (mins),Session Rating,User Name,Age,Location,Registration Date,Phone,Email,Favorite Meal,Total Orders
0,1001.0,2024-12-01,Completed,15.0,Night,5.0,S001,U001,Spaghetti,Dinner,...,30.0,4.5,Alice Johnson,28.0,New York,2023-01-15,123-456-7890,alice@email.com,Dinner,12.0
1,1002.0,2024-12-01,Completed,10.0,Day,4.0,S002,U002,Caesar Salad,Lunch,...,20.0,4.0,Bob Smith,35.0,Los Angeles,2023-02-20,987-654-3210,bob@email.com,Lunch,8.0
2,1003.0,2024-12-02,Canceled,12.5,Night,NaN,S003,U003,Grilled Chicken,Dinner,...,40.0,4.8,Charlie Lee,42.0,Chicago,2023-03-10,555-123-4567,charlie@email.com,Breakfast,15.0
3,1004.0,2024-12-02,Completed,8.0,Morning,4.0,S004,U001,Pancakes,Breakfast,...,30.0,4.2,Alice Johnson,28.0,New York,2023-01-15,123-456-7890,alice@email.com,Dinner,12.0
4,1005.0,2024-12-03,Completed,9.0,Day,4.0,S005,U004,Caesar Salad,Lunch,...,15.0,4.7,David Brown,27.0,San Francisco,2023-04-05,444-333-2222,david@email.com,Dinner,10.0
5,1006.0,2024-12-03,Completed,14.0,Night,4.0,S006,U002,Spaghetti,Dinner,...,30.0,4.3,Bob Smith,35.0,Los Angeles,2023-02-20,987-654-3210,bob@email.com,Lunch,8.0
6,1007.0,2024-12-04,Completed,13.5,Night,4.0,S007,U005,Grilled Chicken,Dinner,...,45.0,4.6,Emma White,30.0,Seattle,2023-05-22,777-888-9999,emma@email.com,Lunch,9.0
7,1008.0,2024-12-04,Canceled,11.0,Day,NaN,S008,U003,Veggie Burger,Lunch,...,20.0,4.4,Charlie Lee,42.0,Chicago,2023-03-10,555-123-4567,charlie@email.com,Breakfast,15.0
8,1009.0,2024-12-05,Completed,12.0,Night,5.0,S009,U001,Grilled Chicken,Dinner,...,40.0,4.9,Alice Johnson,28.0,New York,2023-01-15,123-456-7890,alice@email.com,Dinner,12.0
9,1010.0,2024-12-05,Completed,7.0,Morning,4.0,S010,U002,Oatmeal,Breakfast,...,10.0,4.1,Bob Smith,35.0,Los Angeles,2023-02-20,987-654-3210,bob@email.com,Lunch,8.0
10,1011.0,2024-12-06,Completed,8.5,Morning,4.0,S011,U003,Pancakes,Breakfast,...,30.0,4.6,Charlie Lee,42.0,Chicago,2023-03-10,555-123-4567,charlie@email.com,Breakfast,15.0
11,1012.0,2024-12-06,Completed,12.5,Night,4.0,S012,U004,Spaghetti,Dinner,...,40.0,4.7,David Brown,27.0,San Francisco,2023-04-05,444-333-2222,david@email.com,Dinner,10.0
12,1013.0,2024-12-07,Completed,9.0,Day,4.0,S013,U005,Caesar Salad,Lunch,...,30.0,4.4,Emma White,30.0,Seattle,2023-05-22,777-888-9999,emma@email.com,Lunch,9.0
13,1014.0,2024-12-07,Completed,13.0,Night,5.0,S014,U006,Grilled Chicken,Dinner,...,45.0,4.8,Frank Green,25.0,Austin,2023-06-15,888-777-6666,frank@email.com,Dinner,7.0
14,1015.0,2024-12-08,Completed,14.0,Night,5.0,S015,U007,Spaghetti,Dinner,...,40.0,5.0,Grace King,38.0,Boston,2023-07-02,999-888-7777,grace@email.com,Breakfast,14.0
15,1016.0,2024-12-08,Completed,11.0,Day,4.0,S016,U008,Veggie Burger,Lunch,...,20.0,4.3,Henry Lee,31.0,Miami,2023-08-11,101-202-3030,henry@email.com,Dinner,5.0

In [17]:
merged_data['Rating'] = merged_data['Rating'].fillna(0)

In [18]:
merged_data.to_excel("output.xlsx")